# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harbour-kaktus

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Kaktus
Version:    1.0.3
Release:    1
Group:      Qt/Qt
License:    LICENSE
URL:        https://github.com/mkiol/kaktus
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-kaktus.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(sailfishapp) >= 0.0.10
BuildRequires:  desktop-file-utils

%description
An unofficial Netvibes client for Sailfish OS.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}/qml
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
/usr/bin
/usr/share/harbour-kaktus
/usr/share/applications
/usr/share/icons/hicolor/86x86/apps
# >> files
# << files

%changelog
* Sat Apr 12 2014 Michal Kosciesza 1.0.3-1
- Show only unread option
- Mark all items in Feed as read/unread
- New Cache management algorithm
- Cache size view in Settings
- UI improvements

* Thu Apr 03 2014 Michal Kosciesza 1.0.2-1
- Increased performance
- Better error handling when network connection fails

* Sun Mar 30 2014 Michal Kosciesza 1.0.1-1
- UI improvements
- Extra Tab with Saved items

* Mon Mar 25 2014 Michal Kosciesza 1.0.0-1
- First release
